import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { 
  Calendar, 
  Clock, 
  Star, 
  Sun, 
  Moon, 
  TrendingUp, 
  CalendarDays,
  CalendarRange,
  Sparkles,
  ArrowLeft,
  RefreshCw,
  Download,
  Share2,
  BookOpen,
  Target,
  Loader2,
  Heart,
  DollarSign,
  Briefcase,
  Activity,
  Zap,
  ShieldCheck,
  Compass
} from "lucide-react";
import { 
  getHoroscope, 
  getAllRashis,
  getFormattedDate,
  getPeriodLabel 
} from "../services/horoscope";

// Horoscope Display Component
const HoroscopeDisplay = ({ rashi, period, data, onBack, onPeriodChange, loading }) => {
  if (!data && !loading) {
    return (
      <div className="text-center py-12">
        <p className="text-gray-400">No horoscope data available</p>
        <button
          onClick={onBack}
          className="mt-4 px-4 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold hover:opacity-90 transition-opacity"
        >
          Back to Rashi Selection
        </button>
      </div>
    );
  }

  const getPeriodIcon = (period) => {
    switch(period) {
      case 'daily': return <Clock className="h-5 w-5" />;
      case 'weekly': return <CalendarDays className="h-5 w-5" />;
      case 'monthly': return <Calendar className="h-5 w-5" />;
      case 'yearly': return <CalendarRange className="h-5 w-5" />;
      default: return <Star className="h-5 w-5" />;
    }
  };

  const getPeriodTitle = (period) => {
    return getPeriodLabel(period) + ' Horoscope';
  };

  const formatDate = () => {
    if (!data?.date) {
      return getFormattedDate(period);
    }
    return getFormattedDate(period, data.date);
  };

  const handleDownload = () => {
    if (!data) return;
    
    const content = `
Horoscope Report
================

Date: ${data.date}
Rashi: ${data.rashi}
Period: ${getPeriodLabel(data.period)}

KEY HIGHLIGHTS
-------------
${data.data.prediction}

ADVICE & REMEDIES
----------------
${data.data.advice}

LUCKY FACTORS
-------------
Lucky Number: ${data.data.luckyNumber}
Lucky Color: ${data.data.luckyColor}
Lucky Gem: ${data.data.luckyGem || 'N/A'}
Best Compatibility: ${data.data.compatibility}

RASHI INFORMATION
-----------------
Element: ${data.data.additionalInfo?.element || rashi.element}
Ruling Planet: ${data.data.additionalInfo?.rulingPlanet || rashi.lord}
Best Time: ${data.data.additionalInfo?.bestTime || 'Morning'}
Favorable Direction: ${data.data.additionalInfo?.favorableDirection || 'East'}

---
Generated by RashiBazar
${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `horoscope-${data.rashi}-${data.period}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (!data || !rashi) return;
    
    const text = `Check out my ${getPeriodLabel(data.period)} highlights for ${rashi.name}: "${data.data.prediction.substring(0, 100)}..." #RashiBazar #Horoscope`;
    
    if (navigator.share) {
      navigator.share({
        title: `${rashi.name} ${getPeriodLabel(data.period)} Horoscope`,
        text: text,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(text);
      toast.success('Horoscope copied to clipboard!');
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-4xl mx-auto"
    >
      {/* Back Button */}
      <button
        onClick={onBack}
        className="mb-6 flex items-center gap-2 text-purple-300 hover:text-yellow-400 transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to Rashi Selection
      </button>

      {/* Header */}
      <div className="bg-gradient-to-r from-purple-900/30 to-black/30 rounded-[2.5rem] border-2 border-white/5 p-8 mb-8 backdrop-blur-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/10 rounded-full blur-3xl"></div>
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div className="flex items-center gap-6">
            <div className={`text-6xl ${rashi.color} filter drop-shadow-lg`}>{rashi.symbol}</div>
            <div>
              <h2 className="text-4xl font-black text-white uppercase italic tracking-tighter">{rashi.displayName || rashi.name}</h2>
              <div className="flex flex-wrap items-center gap-3 mt-2">
                <span className="text-sm font-bold text-purple-400 uppercase tracking-widest">{rashi.sanskrit}</span>
                <span className={`text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest ${rashi.bgColor} ${rashi.color} border border-current/20`}>
                  {rashi.element} Element
                </span>
                <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Lord: {rashi.lord}</span>
              </div>
            </div>
          </div>
          
          <div className="flex flex-col items-end">
            <div className="flex items-center gap-2 px-4 py-2 bg-white/5 rounded-2xl border border-white/10">
              {loading ? (
                <Loader2 className="h-4 w-4 animate-spin text-yellow-300" />
              ) : (
                <div className="text-yellow-400">{getPeriodIcon(period)}</div>
              )}
              <span className="text-sm font-black text-white uppercase tracking-widest">{getPeriodTitle(period)}</span>
            </div>
            <div className="mt-2 text-xs font-bold text-gray-500 uppercase tracking-widest">
              {formatDate()}
            </div>
          </div>
        </div>
      </div>

      {/* Loading State */}
      {loading ? (
        <div className="flex justify-center items-center h-96 bg-black/20 rounded-[3rem] border border-dashed border-white/5">
          <div className="text-center">
            <div className="relative inline-block mb-4">
               <Loader2 className="h-16 w-16 animate-spin text-orange-500" />
               <Sparkles className="h-6 w-6 text-yellow-400 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
            </div>
            <p className="text-gray-500 font-black uppercase tracking-[0.3em] text-sm">Consulting Stars...</p>
          </div>
        </div>
      ) : data ? (
        <>
          {/* Main Content */}
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Left Column - Highlights & Advice */}
            <div className="lg:col-span-2 space-y-8">
              {/* Highlights Section (Replaces Detailed Prediction) */}
              <div className="bg-white/5 p-10 rounded-[3rem] border border-white/10 relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-8 opacity-[0.03] group-hover:scale-110 transition-transform duration-700">
                  <Zap className="h-40 w-40 text-yellow-400" />
                </div>
                
                <div className="flex items-center gap-4 mb-8">
                  <div className="h-12 w-12 bg-yellow-400/20 rounded-2xl flex items-center justify-center border border-yellow-400/20">
                    <Zap className="h-6 w-6 text-yellow-400" />
                  </div>
                  <h3 className="text-2xl font-black text-white uppercase italic tracking-tight">Key Highlights</h3>
                </div>
                
                <div className="relative z-10">
                  <p className="text-gray-300 text-xl leading-relaxed font-medium italic">
                    "{data.data.prediction}"
                  </p>
                  
                  <div className="mt-10 pt-8 border-t border-white/5 flex items-start gap-4">
                    <div className="h-10 w-10 bg-emerald-500/20 rounded-xl flex items-center justify-center shrink-0 border border-emerald-500/20">
                      <ShieldCheck className="h-5 w-5 text-emerald-400" />
                    </div>
                    <div>
                      <p className="text-[10px] text-emerald-400 font-black uppercase tracking-widest mb-1">Expert Advice</p>
                      <p className="text-gray-400 text-sm leading-relaxed">{data.data.advice}</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Rashi Info Section (Expanded) */}
              <div className="bg-white/5 p-10 rounded-[3rem] border border-white/10">
                <div className="flex items-center gap-4 mb-8">
                  <div className="h-12 w-12 bg-blue-400/20 rounded-2xl flex items-center justify-center border border-blue-400/20">
                    <Compass className="h-6 w-6 text-blue-400" />
                  </div>
                  <h3 className="text-2xl font-black text-white uppercase italic tracking-tight">Rashi Information</h3>
                </div>
                
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                   {[
                     { label: 'Element', val: data.data.additionalInfo?.element || rashi.element, color: 'text-orange-400' },
                     { label: 'Planet', val: data.data.additionalInfo?.rulingPlanet || rashi.lord, color: 'text-rose-400' },
                     { label: 'Best Time', val: data.data.additionalInfo?.bestTime || 'Morning', color: 'text-yellow-400' },
                     { label: 'Direction', val: data.data.additionalInfo?.favorableDirection || 'East', color: 'text-emerald-400' }
                   ].map((item, i) => (
                     <div key={i} className="bg-black/20 p-5 rounded-[2rem] border border-white/5 text-center">
                        <p className="text-[9px] text-gray-500 font-black uppercase tracking-widest mb-1">{item.label}</p>
                        <p className={`text-sm font-black uppercase ${item.color}`}>{item.val}</p>
                     </div>
                   ))}
                </div>
              </div>
            </div>

            {/* Right Column - Lucky Factors & Actions */}
            <div className="space-y-6">
              {/* Lucky Factors */}
              <div className="bg-gradient-to-br from-orange-500 to-rose-600 p-8 rounded-[2.5rem] shadow-xl shadow-orange-500/10">
                <h4 className="text-lg font-black text-white uppercase italic mb-6">Lucky Factors</h4>
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-black/20 p-4 rounded-2xl backdrop-blur-md">
                    <p className="text-[9px] text-white/50 font-black uppercase tracking-widest mb-1">Number</p>
                    <p className="text-2xl font-black text-white">{data.data.luckyNumber}</p>
                  </div>
                  <div className="bg-black/20 p-4 rounded-2xl backdrop-blur-md">
                    <p className="text-[9px] text-white/50 font-black uppercase tracking-widest mb-1">Color</p>
                    <p className="text-sm font-black text-white uppercase">{data.data.luckyColor}</p>
                  </div>
                  <div className="bg-black/20 p-4 rounded-2xl backdrop-blur-md col-span-2">
                    <p className="text-[9px] text-white/50 font-black uppercase tracking-widest mb-1">Compatible With</p>
                    <p className="text-sm font-black text-white uppercase truncate">{data.data.compatibility}</p>
                  </div>
                </div>
              </div>

              {/* Period Quick Select */}
              <div className="bg-white/5 p-6 rounded-[2.5rem] border border-white/10">
                <h3 className="text-sm font-black text-white uppercase tracking-[0.2em] mb-6 px-2">Forecast Period</h3>
                <div className="grid grid-cols-2 gap-3">
                  {['daily', 'weekly', 'monthly', 'yearly'].map((p) => (
                    <button
                      key={p}
                      disabled={loading}
                      onClick={() => onPeriodChange(p)}
                      className={`p-4 rounded-2xl text-xs font-black uppercase tracking-widest transition-all ${
                        period === p
                          ? 'bg-white text-black shadow-lg'
                          : 'bg-white/5 text-gray-500 hover:bg-white/10 hover:text-white'
                      }`}
                    >
                      {p}
                    </button>
                  ))}
                </div>
              </div>

              {/* Actions */}
              <div className="flex gap-4">
                <button 
                  onClick={handleDownload}
                  className="flex-1 h-16 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 transition-all"
                >
                  <Download className="h-6 w-6" />
                </button>
                <button 
                  onClick={handleShare}
                  className="flex-1 h-16 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 transition-all"
                >
                  <Share2 className="h-6 w-6" />
                </button>
              </div>
            </div>
          </div>
        </>
      ) : null}
    </motion.div>
  );
};

// Main Horoscope Component (Existing logic preserved, but visual updated to premium)
const Horoscope = () => {
  const [selectedRashi, setSelectedRashi] = useState(null);
  const [selectedPeriod, setSelectedPeriod] = useState('daily');
  const [horoscopeData, setHoroscopeData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [rashis, setRashis] = useState([]);
  const [error, setError] = useState(null);

  useEffect(() => { loadRashis(); }, []);
  useEffect(() => { if (selectedRashi) loadHoroscope(); }, [selectedRashi, selectedPeriod]);

  const loadRashis = async () => {
    try {
      const response = await getAllRashis();
      if (response.success && response.rashis) {
        setRashis(response.rashis.map(rashi => ({
          ...rashi,
          color: getColorForRashi(rashi.name),
          bgColor: getBgColorForRashi(rashi.name),
          borderColor: getBorderColorForRashi(rashi.name)
        })));
      } else { setRashis(defaultRashis); }
    } catch (error) { setRashis(defaultRashis); }
  };

  const loadHoroscope = async () => {
    if (!selectedRashi) return;
    setLoading(true);
    setHoroscopeData(null);
    setError(null);
    try {
      const data = await getHoroscope(selectedRashi.name, selectedPeriod);
      setHoroscopeData(data);
    } catch (error) {
      setError("Unable to sync with planetary energies. Retrying...");
      // Auto-retry or fallback logic
    } finally { setLoading(false); }
  };

  const handleRashiClick = (rashi) => {
    setSelectedRashi(rashi);
    setSelectedPeriod('daily');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const getColorForRashi = (n) => {
    const c = { Aries:'text-red-400', Taurus:'text-emerald-400', Gemini:'text-yellow-400', Cancer:'text-slate-400', Leo:'text-orange-400', Virgo:'text-teal-300', Libra:'text-pink-400', Scorpio:'text-rose-400', Sagittarius:'text-indigo-400', Capricorn:'text-amber-700', Aquarius:'text-sky-400', Pisces:'text-cyan-400' };
    return c[n] || 'text-white';
  };
  const getBgColorForRashi = (n) => {
    const b = { Aries:'bg-red-400/5', Taurus:'bg-emerald-400/5', Gemini:'bg-yellow-400/5', Cancer:'bg-slate-400/5', Leo:'bg-orange-400/5', Virgo:'bg-teal-300/5', Libra:'bg-pink-400/5', Scorpio:'bg-rose-400/5', Sagittarius:'bg-indigo-400/5', Capricorn:'bg-amber-700/5', Aquarius:'bg-sky-400/5', Pisces:'bg-cyan-400/5' };
    return b[n] || 'bg-white/5';
  };
  const getBorderColorForRashi = (n) => {
     const bc = { Aries:'border-red-400/20', Taurus:'border-emerald-400/20', Gemini:'border-yellow-400/20', Cancer:'border-slate-400/20', Leo:'border-orange-400/20', Virgo:'border-teal-300/20', Libra:'border-pink-400/20', Scorpio:'border-rose-400/20', Sagittarius:'border-indigo-400/20', Capricorn:'border-amber-700/20', Aquarius:'border-sky-400/20', Pisces:'border-cyan-400/20' };
     return bc[n] || 'border-white/10';
  };

  const defaultRashis = [
    { name: "Aries", displayName: "Mesh", symbol: "♈", sanskrit: "मेष", element: "Fire", lord: "Mars" },
    { name: "Taurus", displayName: "Vrishabh", symbol: "♉", sanskrit: "वृषभ", element: "Earth", lord: "Venus" },
    { name: "Gemini", displayName: "Mithun", symbol: "♊", sanskrit: "मिथुन", element: "Air", lord: "Mercury" },
    { name: "Cancer", displayName: "Kark", symbol: "♋", sanskrit: "कर्क", element: "Water", lord: "Moon" },
    { name: "Leo", displayName: "Simha", symbol: "♌", sanskrit: "सिंह", element: "Fire", lord: "Sun" },
    { name: "Virgo", displayName: "Kanya", symbol: "♍", sanskrit: "कन्या", element: "Earth", lord: "Mercury" },
    { name: "Libra", displayName: "Tula", symbol: "♎", sanskrit: "तुला", element: "Air", lord: "Venus" },
    { name: "Scorpio", displayName: "Vrishchik", symbol: "♏", sanskrit: "वृश्चिक", element: "Water", lord: "Mars" },
    { name: "Sagittarius", displayName: "Dhanu", symbol: "♐", sanskrit: "धनु", element: "Fire", lord: "Jupiter" },
    { name: "Capricorn", displayName: "Makar", symbol: "♑", sanskrit: "मेष", element: "Earth", lord: "Saturn" },
    { name: "Aquarius", displayName: "Kumbh", symbol: "♒", sanskrit: "कुम्भ", element: "Air", lord: "Saturn" },
    { name: "Pisces", displayName: "Meen", symbol: "♓", sanskrit: "मीन", element: "Water", lord: "Jupiter" }
  ];

  return (
    <div className="pt-32 min-h-screen px-4 md:px-12 text-white bg-[#050505]">
      <div className="max-w-7xl mx-auto">
        {!selectedRashi ? (
          <>
            <header className="text-center mb-24">
              <h1 className="text-7xl font-black text-white uppercase italic tracking-tighter mb-4">The Horoscope</h1>
              <p className="text-gray-500 font-bold uppercase tracking-[0.4em] text-xs">Vedic Astrology • Managed Way</p>
            </header>

            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-6">
              {(rashis.length > 0 ? rashis : defaultRashis).map((r, i) => (
                <motion.div
                  key={r.name}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  onClick={() => handleRashiClick(r)}
                  className={`p-10 rounded-[3rem] ${r.bgColor || 'bg-white/5'} border ${r.borderColor || 'border-white/10'} hover:border-orange-500/50 cursor-pointer transition-all duration-500 group text-center relative overflow-hidden`}
                >
                   <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-orange-500/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                   <div className={`text-6xl mb-6 ${r.color} group-hover:scale-110 group-hover:rotate-6 transition-transform duration-500`}>{r.symbol}</div>
                   <h3 className="text-lg font-black text-white uppercase italic tracking-tight">{r.displayName || r.name}</h3>
                   <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest mt-2">{r.sanskrit}</p>
                </motion.div>
              ))}
            </div>
          </>
        ) : (
          <HoroscopeDisplay 
            rashi={selectedRashi} 
            period={selectedPeriod} 
            data={horoscopeData} 
            loading={loading}
            onBack={() => setSelectedRashi(null)}
            onPeriodChange={setSelectedPeriod}
          />
        )}
      </div>
    </div>
  );
};

export default Horoscope;