import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { 
  Calendar, 
  Clock, 
  Star, 
  Sun, 
  Moon, 
  TrendingUp, 
  CalendarDays,
  CalendarRange,
  Sparkles,
  ArrowLeft,
  RefreshCw,
  Download,
  Share2,
  BookOpen,
  Target,
  Loader2,
  Heart,
  DollarSign,
  Briefcase,
  Activity
} from "lucide-react";
import { 
  getHoroscope, 
  getAllRashis,
  getFormattedDate,
  getPeriodLabel 
} from "../services/horoscope";

// Horoscope Display Component
const HoroscopeDisplay = ({ rashi, period, data, onBack, onPeriodChange, loading }) => {
  if (!data && !loading) {
    return (
      <div className="text-center py-12">
        <p className="text-gray-400">No horoscope data available</p>
        <button
          onClick={onBack}
          className="mt-4 px-4 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold hover:opacity-90 transition-opacity"
        >
          Back to Rashi Selection
        </button>
      </div>
    );
  }

  const getPeriodIcon = (period) => {
    switch(period) {
      case 'daily': return <Clock className="h-5 w-5" />;
      case 'weekly': return <CalendarDays className="h-5 w-5" />;
      case 'monthly': return <Calendar className="h-5 w-5" />;
      case 'yearly': return <CalendarRange className="h-5 w-5" />;
      default: return <Star className="h-5 w-5" />;
    }
  };

  const getPeriodTitle = (period) => {
    return getPeriodLabel(period) + ' Horoscope';
  };

  const formatDate = () => {
    if (!data?.date) {
      return getFormattedDate(period);
    }
    return getFormattedDate(period, data.date);
  };

  const handleDownload = () => {
    if (!data) return;
    
    const content = `
Horoscope Report
================

Date: ${data.date}
Rashi: ${data.rashi}
Period: ${getPeriodLabel(data.period)}

PREDICTION
----------
${data.data.prediction}

ADVICE
------
${data.data.advice}

KEY HIGHLIGHTS
-------------
Lucky Number: ${data.data.luckyNumber}
Lucky Color: ${data.data.luckyColor}
Best Compatibility: ${data.data.compatibility}

CATEGORY PREDICTIONS
-------------------
Career: ${data.data.categoryPredictions?.career || 'Not available'}
Love: ${data.data.categoryPredictions?.love || 'Not available'}
Health: ${data.data.categoryPredictions?.health || 'Not available'}
Finance: ${data.data.categoryPredictions?.finance || 'Not available'}

ADDITIONAL INFO
---------------
Element: ${data.data.additionalInfo?.element || 'Not available'}
Ruling Planet: ${data.data.additionalInfo?.rulingPlanet || 'Not available'}
Quality: ${data.data.additionalInfo?.quality || 'Not available'}
Best Time: ${data.data.additionalInfo?.bestTime || 'Not available'}
Favorable Direction: ${data.data.additionalInfo?.favorableDirection || 'Not available'}

---
Generated by RashiBazar
${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `horoscope-${data.rashi}-${data.period}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (!data || !rashi) return;
    
    const text = `Check out my ${getPeriodLabel(data.period)} horoscope for ${rashi.name}: "${data.data.prediction.substring(0, 100)}..." #RashiBazar #Horoscope`;
    
    if (navigator.share) {
      navigator.share({
        title: `${rashi.name} ${getPeriodLabel(data.period)} Horoscope`,
        text: text,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(text);
      alert('Horoscope copied to clipboard!');
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-4xl mx-auto"
    >
      {/* Back Button */}
      <button
        onClick={onBack}
        className="mb-6 flex items-center gap-2 text-purple-300 hover:text-yellow-400 transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to Rashi Selection
      </button>

      {/* Header */}
      <div className="bg-gradient-to-r from-purple-900/30 to-black/30 rounded-2xl border-2 border-purple-700/30 p-6 mb-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className={`text-5xl ${rashi.color}`}>{rashi.symbol}</div>
            <div>
              <h2 className="text-3xl font-bold text-white">{rashi.displayName || rashi.name}</h2>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-sm text-gray-400">{rashi.sanskrit}</span>
                <span className={`text-xs px-2 py-1 rounded-full ${rashi.bgColor} ${rashi.color}`}>
                  {rashi.element}
                </span>
                <span className="text-sm text-gray-400">Ruling Planet: {rashi.lord}</span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {loading ? (
              <Loader2 className="h-5 w-5 animate-spin text-yellow-300" />
            ) : (
              getPeriodIcon(period)
            )}
            <span className="text-xl font-bold text-yellow-300">{getPeriodTitle(period)}</span>
          </div>
        </div>
        <div className="mt-4 text-center text-gray-300">
          {formatDate()}
        </div>
      </div>

      {/* Loading State */}
      {loading ? (
        <div className="flex justify-center items-center h-64">
          <div className="text-center">
            <Loader2 className="h-12 w-12 animate-spin text-yellow-400 mx-auto mb-4" />
            <p className="text-gray-300">Loading your horoscope...</p>
          </div>
        </div>
      ) : data ? (
        <>
          {/* Main Content */}
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Left Column - Prediction */}
            <div className="lg:col-span-2">
              <div className="bg-black/30 p-6 rounded-2xl border-2 border-purple-700/30 mb-6">
                <div className="flex items-center gap-3 mb-4">
                  <BookOpen className="h-6 w-6 text-blue-400" />
                  <h3 className="text-xl font-bold text-blue-300">Prediction</h3>
                </div>
                <div className="space-y-4">
                  <p className="text-gray-300 text-lg leading-relaxed">{data.data.prediction}</p>
                  <div className="p-4 bg-black/50 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-yellow-400" />
                      <span className="text-yellow-300 font-semibold">Special Advice:</span>
                    </div>
                    <p className="text-gray-300">{data.data.advice}</p>
                  </div>
                </div>
              </div>

              {/* Category Predictions */}
              {data.data.categoryPredictions && (
                <div className="bg-black/30 p-6 rounded-2xl border-2 border-blue-700/30 mb-6">
                  <div className="flex items-center gap-3 mb-6">
                    <TrendingUp className="h-6 w-6 text-green-400" />
                    <h3 className="text-xl font-bold text-green-300">Detailed Predictions</h3>
                  </div>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div className="p-4 bg-black/50 rounded-lg">
                        <div className="flex items-center gap-2 mb-2">
                          <Briefcase className="h-4 w-4 text-blue-400" />
                          <span className="text-sm text-gray-400">Career</span>
                        </div>
                        <div className="text-gray-300">{data.data.categoryPredictions.career}</div>
                      </div>
                      <div className="p-4 bg-black/50 rounded-lg">
                        <div className="flex items-center gap-2 mb-2">
                          <Activity className="h-4 w-4 text-green-400" />
                          <span className="text-sm text-gray-400">Health</span>
                        </div>
                        <div className="text-gray-300">{data.data.categoryPredictions.health}</div>
                      </div>
                    </div>
                    <div className="space-y-4">
                      <div className="p-4 bg-black/50 rounded-lg">
                        <div className="flex items-center gap-2 mb-2">
                          <Heart className="h-4 w-4 text-pink-400" />
                          <span className="text-sm text-gray-400">Love</span>
                        </div>
                        <div className="text-gray-300">{data.data.categoryPredictions.love}</div>
                      </div>
                      <div className="p-4 bg-black/50 rounded-lg">
                        <div className="flex items-center gap-2 mb-2">
                          <DollarSign className="h-4 w-4 text-yellow-400" />
                          <span className="text-sm text-gray-400">Finance</span>
                        </div>
                        <div className="text-gray-300">{data.data.categoryPredictions.finance}</div>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Additional Insights */}
              <div className="bg-black/30 p-6 rounded-2xl border-2 border-green-700/30">
                <div className="flex items-center gap-3 mb-6">
                  <Sparkles className="h-6 w-6 text-green-400" />
                  <h3 className="text-xl font-bold text-green-300">Key Highlights</h3>
                </div>
                <div className="grid md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="p-4 bg-black/50 rounded-lg">
                      <div className="text-sm text-gray-400">Lucky Number</div>
                      <div className="text-3xl font-bold text-yellow-300">{data.data.luckyNumber}</div>
                    </div>
                    <div className="p-4 bg-black/50 rounded-lg">
                      <div className="text-sm text-gray-400">Lucky Color</div>
                      <div className="text-2xl font-bold" style={{ color: data.data.luckyColor.toLowerCase() }}>
                        {data.data.luckyColor}
                      </div>
                    </div>
                  </div>
                  <div className="space-y-4">
                    <div className="p-4 bg-black/50 rounded-lg">
                      <div className="text-sm text-gray-400">Best Compatibility</div>
                      <div className="text-2xl font-bold text-pink-300">{data.data.compatibility}</div>
                    </div>
                    <div className="p-4 bg-black/50 rounded-lg">
                      <div className="text-sm text-gray-400">Period</div>
                      <div className="text-xl font-bold text-white">{formatDate()}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column - Actions and Info */}
            <div className="space-y-6">
              {/* Period Selection */}
              <div className="bg-black/30 p-6 rounded-2xl border-2 border-purple-700/30">
                <h3 className="text-lg font-bold text-yellow-300 mb-4">Select Period</h3>
                <div className="space-y-3">
                  {['daily', 'weekly', 'monthly', 'yearly'].map((p) => (
                    <button
                      key={p}
                      disabled={loading}
                      className={`w-full p-3 rounded-lg text-left transition-all ${
                        period === p
                          ? 'bg-gradient-to-r from-yellow-400/20 to-orange-500/20 border-2 border-yellow-400/50'
                          : 'bg-black/50 border border-purple-700/30 hover:bg-purple-900/20'
                      } ${loading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                      onClick={() => onPeriodChange(p)}
                    >
                      <div className="flex items-center gap-3">
                        {getPeriodIcon(p)}
                        <span className="font-semibold text-white capitalize">{getPeriodLabel(p)} Horoscope</span>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Actions */}
              <div className="bg-black/30 p-6 rounded-2xl border-2 border-green-700/30">
                <div className="space-y-3">
                  <button 
                    onClick={handleDownload}
                    disabled={!data}
                    className="w-full p-3 bg-gradient-to-r from-yellow-500 to-orange-500 text-black rounded-lg font-bold hover:opacity-90 transition-opacity flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <Download className="h-5 w-5" />
                    Download Report
                  </button>
                  <button 
                    onClick={handleShare}
                    disabled={!data}
                    className="w-full p-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold hover:opacity-90 transition-opacity flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <Share2 className="h-5 w-5" />
                    Share Horoscope
                  </button>
                  <button 
                    onClick={() => onPeriodChange(period)}
                    disabled={loading}
                    className="w-full p-3 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-lg font-bold hover:opacity-90 transition-opacity flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <RefreshCw className="h-5 w-5" />
                    Refresh
                  </button>
                </div>
              </div>

              {/* Rashi Info */}
              <div className="bg-black/30 p-6 rounded-2xl border-2 border-blue-700/30">
                <div className="flex items-center gap-3 mb-4">
                  <Sun className="h-6 w-6 text-yellow-400" />
                  <h3 className="text-lg font-bold text-yellow-300">Rashi Information</h3>
                </div>
                <div className="space-y-3 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-400">Element:</span>
                    <span className="text-white">{rashi.element}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Ruling Planet:</span>
                    <span className="text-white">{rashi.lord}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Quality:</span>
                    <span className="text-white">{rashi.quality}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Best Time:</span>
                    <span className="text-white">{data.data.additionalInfo?.bestTime || 'Morning'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-400">Direction:</span>
                    <span className="text-white">{data.data.additionalInfo?.favorableDirection || 'East'}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : null}
    </motion.div>
  );
};

// Main Horoscope Component
const Horoscope = () => {
  const [selectedRashi, setSelectedRashi] = useState(null);
  const [selectedPeriod, setSelectedPeriod] = useState('daily');
  const [horoscopeData, setHoroscopeData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [rashis, setRashis] = useState([]);
  const [error, setError] = useState(null);

  // Load rashis on component mount
  useEffect(() => {
    loadRashis();
  }, []);

  // Load horoscope when rashi or period changes
  useEffect(() => {
    if (selectedRashi) {
      loadHoroscope();
    }
  }, [selectedRashi, selectedPeriod]);

  const loadRashis = async () => {
    try {
      const response = await getAllRashis();
      if (response.success && response.rashis) {
        // Map backend rashis to frontend format
        const formattedRashis = response.rashis.map(rashi => ({
          ...rashi,
          color: getColorForRashi(rashi.name),
          bgColor: getBgColorForRashi(rashi.name),
          borderColor: getBorderColorForRashi(rashi.name)
        }));
        setRashis(formattedRashis);
      } else {
        // Fallback to default rashis
        setRashis(defaultRashis);
      }
    } catch (error) {
      console.error("Error loading rashis:", error);
      setRashis(defaultRashis);
    }
  };

  const loadHoroscope = async () => {
    if (!selectedRashi) return;
    
    setLoading(true);
    setHoroscopeData(null);
    setError(null);
    
    try {
      const data = await getHoroscope(selectedRashi.name, selectedPeriod);
      setHoroscopeData(data);
    } catch (error) {
      console.error("Error loading horoscope:", error);
      setError("Failed to load horoscope. Please try again.");
      setHoroscopeData({
        success: true,
        rashi: selectedRashi.name,
        period: selectedPeriod,
        date: new Date().toISOString().split('T')[0],
        data: {
          prediction: `Unable to fetch real horoscope data. Please check your connection and try again. Sample prediction for ${selectedRashi.name}: Positive energies surround you this ${selectedPeriod}.`,
          luckyNumber: Math.floor(Math.random() * 30) + 1,
          luckyColor: "Red",
          compatibility: "Gemini",
          advice: "Stay positive and trust the process.",
          additionalInfo: {
            element: selectedRashi.element,
            rulingPlanet: selectedRashi.lord,
            quality: selectedRashi.quality,
            bestTime: "Morning",
            favorableDirection: "East"
          },
          categoryPredictions: {
            career: "Career growth opportunities ahead.",
            love: "Relationships will flourish.",
            health: "Maintain a balanced lifestyle.",
            finance: "Financial stability is assured."
          }
        }
      });
    } finally {
      setLoading(false);
    }
  };

  const handleRashiClick = (rashi) => {
    setSelectedRashi(rashi);
    setSelectedPeriod('daily');
    setHoroscopeData(null);
    setError(null);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleBack = () => {
    setSelectedRashi(null);
    setHoroscopeData(null);
    setSelectedPeriod('daily');
    setError(null);
  };

  const handlePeriodChange = (period) => {
    setSelectedPeriod(period);
  };

  // Helper functions for styling
  const getColorForRashi = (rashiName) => {
    const colors = {
      'Aries': 'text-red-400',
      'Taurus': 'text-green-400',
      'Gemini': 'text-yellow-400',
      'Cancer': 'text-gray-400',
      'Leo': 'text-orange-400',
      'Virgo': 'text-green-300',
      'Libra': 'text-pink-400',
      'Scorpio': 'text-red-300',
      'Sagittarius': 'text-purple-400',
      'Capricorn': 'text-amber-700',
      'Aquarius': 'text-blue-400',
      'Pisces': 'text-teal-400'
    };
    return colors[rashiName] || 'text-white';
  };

  const getBgColorForRashi = (rashiName) => {
    const bgColors = {
      'Aries': 'bg-red-400/10',
      'Taurus': 'bg-green-400/10',
      'Gemini': 'bg-yellow-400/10',
      'Cancer': 'bg-gray-400/10',
      'Leo': 'bg-orange-400/10',
      'Virgo': 'bg-green-300/10',
      'Libra': 'bg-pink-400/10',
      'Scorpio': 'bg-red-300/10',
      'Sagittarius': 'bg-purple-400/10',
      'Capricorn': 'bg-amber-700/10',
      'Aquarius': 'bg-blue-400/10',
      'Pisces': 'bg-teal-400/10'
    };
    return bgColors[rashiName] || 'bg-white/10';
  };

  const getBorderColorForRashi = (rashiName) => {
    const borderColors = {
      'Aries': 'border-red-400/30',
      'Taurus': 'border-green-400/30',
      'Gemini': 'border-yellow-400/30',
      'Cancer': 'border-gray-400/30',
      'Leo': 'border-orange-400/30',
      'Virgo': 'border-green-300/30',
      'Libra': 'border-pink-400/30',
      'Scorpio': 'border-red-300/30',
      'Sagittarius': 'border-purple-400/30',
      'Capricorn': 'border-amber-700/30',
      'Aquarius': 'border-blue-400/30',
      'Pisces': 'border-teal-400/30'
    };
    return borderColors[rashiName] || 'border-white/30';
  };

  // Default rashis if API fails
  const defaultRashis = [
    { 
      name: "Aries", 
      displayName: "Aries (Mesh)",
      symbol: "♈",
      sanskrit: "मेष",
      element: "Fire",
      lord: "Mars",
      quality: "Cardinal",
      color: "text-red-400",
      bgColor: "bg-red-400/10",
      borderColor: "border-red-400/30"
    },
    { 
      name: "Taurus", 
      displayName: "Taurus (Vrishabh)",
      symbol: "♉",
      sanskrit: "वृषभ",
      element: "Earth",
      lord: "Venus",
      quality: "Fixed",
      color: "text-green-400",
      bgColor: "bg-green-400/10",
      borderColor: "border-green-400/30"
    },
    { 
      name: "Gemini", 
      displayName: "Gemini (Mithun)",
      symbol: "♊",
      sanskrit: "मिथुन",
      element: "Air",
      lord: "Mercury",
      quality: "Mutable",
      color: "text-yellow-400",
      bgColor: "bg-yellow-400/10",
      borderColor: "border-yellow-400/30"
    },
    { 
      name: "Cancer", 
      displayName: "Cancer (Kark)",
      symbol: "♋",
      sanskrit: "कर्क",
      element: "Water",
      lord: "Moon",
      quality: "Cardinal",
      color: "text-gray-400",
      bgColor: "bg-gray-400/10",
      borderColor: "border-gray-400/30"
    },
    { 
      name: "Leo", 
      displayName: "Leo (Simha)",
      symbol: "♌",
      sanskrit: "सिंह",
      element: "Fire",
      lord: "Sun",
      quality: "Fixed",
      color: "text-orange-400",
      bgColor: "bg-orange-400/10",
      borderColor: "border-orange-400/30"
    },
    { 
      name: "Virgo", 
      displayName: "Virgo (Kanya)",
      symbol: "♍",
      sanskrit: "कन्या",
      element: "Earth",
      lord: "Mercury",
      quality: "Mutable",
      color: "text-green-300",
      bgColor: "bg-green-300/10",
      borderColor: "border-green-300/30"
    },
    { 
      name: "Libra", 
      displayName: "Libra (Tula)",
      symbol: "♎",
      sanskrit: "तुला",
      element: "Air",
      lord: "Venus",
      quality: "Cardinal",
      color: "text-pink-400",
      bgColor: "bg-pink-400/10",
      borderColor: "border-pink-400/30"
    },
    { 
      name: "Scorpio", 
      displayName: "Scorpio (Vrishchik)",
      symbol: "♏",
      sanskrit: "वृश्चिक",
      element: "Water",
      lord: "Mars",
      quality: "Fixed",
      color: "text-red-300",
      bgColor: "bg-red-300/10",
      borderColor: "border-red-300/30"
    },
    { 
      name: "Sagittarius", 
      displayName: "Sagittarius (Dhanu)",
      symbol: "♐",
      sanskrit: "धनु",
      element: "Fire",
      lord: "Jupiter",
      quality: "Mutable",
      color: "text-purple-400",
      bgColor: "bg-purple-400/10",
      borderColor: "border-purple-400/30"
    },
    { 
      name: "Capricorn", 
      displayName: "Capricorn (Makar)",
      symbol: "♑",
      sanskrit: "मकर",
      element: "Earth",
      lord: "Saturn",
      quality: "Cardinal",
      color: "text-amber-700",
      bgColor: "bg-amber-700/10",
      borderColor: "border-amber-700/30"
    },
    { 
      name: "Aquarius", 
      displayName: "Aquarius (Kumbh)",
      symbol: "♒",
      sanskrit: "कुम्भ",
      element: "Air",
      lord: "Saturn",
      quality: "Fixed",
      color: "text-blue-400",
      bgColor: "bg-blue-400/10",
      borderColor: "border-blue-400/30"
    },
    { 
      name: "Pisces", 
      displayName: "Pisces (Meen)",
      symbol: "♓",
      sanskrit: "मीन",
      element: "Water",
      lord: "Jupiter",
      quality: "Mutable",
      color: "text-teal-400",
      bgColor: "bg-teal-400/10",
      borderColor: "border-teal-400/30"
    }
  ];

  const displayRashis = rashis.length > 0 ? rashis : defaultRashis;

  return (
    <div className="pt-24 min-h-screen px-4 md:px-6 text-white bg-gradient-to-b from-black via-purple-950 to-black">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl md:text-6xl font-bold mb-4 bg-gradient-to-r from-yellow-400 via-pink-400 to-purple-500 bg-clip-text text-transparent">
            🔮 राशिफल
          </h1>
          <p className="text-gray-300 text-xl">
            Get your personalized daily, weekly, monthly, and yearly horoscope based on Vedic astrology
          </p>
          <div className="mt-4 flex justify-center gap-4">
            <div className="flex items-center gap-2 text-sm text-gray-400">
              <Clock className="h-4 w-4" />
              Updated Daily
            </div>
            <div className="flex items-center gap-2 text-sm text-gray-400">
              <Star className="h-4 w-4" />
              Based on Vedic Astrology
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-6 p-4 bg-red-900/30 border border-red-700/50 rounded-lg">
            <p className="text-red-300">{error}</p>
          </div>
        )}

        {/* Main Content */}
        {!selectedRashi ? (
          <>
            {/* Rashis Grid */}
            <section className="mb-16">
              <div className="flex items-center justify-center gap-3 mb-8">
                <Sun className="h-8 w-8 text-yellow-400" />
                <Moon className="h-8 w-8 text-blue-400" />
                <h2 className="text-4xl font-bold text-center text-yellow-300">
                  12 Zodiac Signs (राशि)
                </h2>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                {displayRashis.map((rashi, index) => (
                  <motion.div
                    key={rashi.name}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    whileHover={{ scale: 1.05, y: -5 }}
                    onClick={() => handleRashiClick(rashi)}
                    className={`p-6 rounded-2xl ${rashi.bgColor} border-2 ${rashi.borderColor} hover:border-yellow-400/50 cursor-pointer transition-all duration-300 hover:shadow-2xl hover:shadow-purple-500/20`}
                  >
                    <div className="text-center">
                      <div className={`text-6xl mb-4 ${rashi.color}`}>{rashi.symbol}</div>
                      <h3 className="text-xl font-bold text-white mb-2">{rashi.displayName || rashi.name}</h3>
                      <div className="text-sm text-gray-300 mb-3">{rashi.sanskrit}</div>
                      <div className="flex justify-center gap-3">
                        <span className={`text-xs px-2 py-1 rounded-full ${rashi.bgColor} ${rashi.color}`}>
                          {rashi.element}
                        </span>
                        <span className="text-xs px-2 py-1 rounded-full bg-black/50 text-gray-300">
                          {rashi.lord}
                        </span>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>

              <div className="mt-12 text-center">
                <p className="text-gray-400 max-w-2xl mx-auto">
                  Select your Rashi to get detailed horoscope predictions for daily, weekly, monthly, and yearly periods based on planetary movements and Vedic astrology principles.
                </p>
              </div>
            </section>

            {/* Quick Info */}
            <section className="bg-black/30 p-8 rounded-2xl border-2 border-purple-700/30">
              <div className="grid md:grid-cols-4 gap-8">
                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-r from-yellow-400/10 to-orange-500/10 mb-4">
                    <Clock className="h-8 w-8 text-yellow-400" />
                  </div>
                  <h3 className="text-xl font-bold text-yellow-300 mb-2">Daily Predictions</h3>
                  <p className="text-gray-400">Daily guidance and insights for your day ahead</p>
                </div>
                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-r from-purple-500/10 to-pink-500/10 mb-4">
                    <CalendarDays className="h-8 w-8 text-purple-400" />
                  </div>
                  <h3 className="text-xl font-bold text-purple-300 mb-2">Weekly Forecast</h3>
                  <p className="text-gray-400">Detailed predictions for the upcoming week</p>
                </div>
                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-r from-blue-500/10 to-cyan-500/10 mb-4">
                    <Calendar className="h-8 w-8 text-blue-400" />
                  </div>
                  <h3 className="text-xl font-bold text-blue-300 mb-2">Monthly Overview</h3>
                  <p className="text-gray-400">Complete monthly analysis with important dates</p>
                </div>
                <div className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-r from-green-500/10 to-teal-500/10 mb-4">
                    <CalendarRange className="h-8 w-8 text-green-400" />
                  </div>
                  <h3 className="text-xl font-bold text-green-300 mb-2">Yearly Forecast</h3>
                  <p className="text-gray-400">Annual predictions for all aspects of life</p>
                </div>
              </div>
            </section>
          </>
        ) : (
          <HoroscopeDisplay
            rashi={selectedRashi}
            period={selectedPeriod}
            data={horoscopeData}
            onBack={handleBack}
            onPeriodChange={handlePeriodChange}
            loading={loading}
          />
        )}

        {/* Footer Note */}
        <div className="mt-16 text-center text-gray-500 text-sm">
          <p>Note: Horoscope predictions are based on Vedic astrology calculations using Lahiri Ayanamsa</p>
          <p className="mt-1">Predictions are for guidance only. Actual results may vary based on individual karma and free will.</p>
        </div>
      </div>
    </div>
  );
};

export default Horoscope;